### PR TITLE
[update image + process]

### PR DESCRIPTION
**Pull request by robbdempsey**
this changes up the approach to how the original worked.  After having issues with images and then volumes I found this to be an easier path.  It works but I'm not sure what we need to do with the blog posts that exists in a different context.

### CODE REVIEW

**Comment by darahayes** [comment]
Hey folks, hope all is well! I got an email notification about this PR so I thought I'd drop a line now that I work with OpenShift every day.

I know this entire repo is all about minishift and I'm not sure of your use case anymore but it might also be worth looking at the new `oc cluster up` command which did not exist at the time we started this demo. `oc cluster up` starts OpenShift using plain docker.

It doesn't require any VM setup and it's a whole lot faster and less resource intensive than minishift. [See the docs] (https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) to get a full understanding of the advantages/disadvantages.

**Comment by conoro** [comment]
Hey good to hear from you @darahayes . Sounds like a better approach. WDYT @robbdempsey ?

**Comment by Elexy** [comment]
I just ran the instructions from the README on this branch and got an error
```

npm ERR! Failed to parse json
--
  | npm ERR! Unexpected token } in JSON at position 210 while parsing near '...mon -L index.js",
  | npm ERR!   },
  | npm ERR!   "dependencies":...'
  | npm ERR! File: /tmp/package.json
  | npm ERR! Failed to parse package.json data.
  | npm ERR! package.json must be actual JSON, not just JavaScript.


```

**Comment by robbdempsey** [comment]
@conoro I was unable to get the registry working using the `oc cluster up` approach.  So I decided to roll back and get the `mini-shift` version working.  with this last push this should work and deploy a pod with the original code.

**Comment by robbdempsey** [comment]
@conoro that last pushes us across the line.

**Comment by conoro** [comment]
Awesome, thanks @robbdempsey . Is the blogpost updated too? Can you add a comment at the start about it being updated and possibly add [UPDATED] in the title and set date to Friday morning and we'll re-publish it then? Don't want to clash with the Node 10.x release post today.

**Pull request merged**
